mountaincar:
  episodes: 75000
  buffer_size: 50000
  max_steps: 200
  gamma: 0.99
  lr: 0.0005
  tau: 0.005
  min_epsilon: 0.05
  max_epsilon: 1.0
  decay_rate: 0.00005
  batch_size: 64
  prefill_episodes: 50
  prefill_epsilon: 0.2
  n_step: 3
  batch_size: 64

# mountaincar:
#   episodes: 75000
#   buffer_size: 50000
#   max_steps: 200
#   gamma: 0.99
#   lr: 0.0003
#   tau: 0.005
#   min_epsilon: 0.05
#   max_epsilon: 1.0
#   decay_rate: 0.00002
#   batch_size: 64
#   prefill_episodes: 50
#   prefill_epsilon: 0.2
#   n_step: 3
#   batch_size: 64

xtra:
  seed: 42